## Arrays

- An array is a collection of elements that are stored at contiguous memory locations. It is a container of similar items placed in contiguous memory  locations.
- Ways to Implement:
    - Using Lists
    - Using Arrays module 
    - Using NumPy array module




In [4]:
# Importing
import array as arr

array1 = arr.array('i', [1,2,3,4,5]) # i refers to integer value (typecode)
print(array1)

array2 = arr.array('d', [1.2, 3.4, 4.0, 2.5, 3.7, 8.0])
print(array2)



array('i', [1, 2, 3, 4, 5])
array('d', [1.2, 3.4, 4.0, 2.5, 3.7, 8.0])


In [5]:
# length of array
print(len(array1))
print(len(array2))

5
6


In [10]:
# Accessing elements:

print("Elements of Array1: ")
for i in range(0, len(array1)): # Using for loop to iterate over each element of array.
    print(array1[i], end=" ") # giving end =" " to get answer in same row.
print()

print("Elements of Array2: ")
for i in range(0, len(array2)):
    print(array2[i], end=" ")


Elements of Array1: 
1 2 3 4 5 
Elements of Array2: 
1.2 3.4 4.0 2.5 3.7 8.0 

**Indexing:**

- Indexing is the way to access the elements of an array.
- Indexing starts from 0
- Negative indexing is also possible    

In [19]:
# Example:
x = arr.array('i', range(1,101,3)) # instead of writing numbers, used range function to make an array
print(x)

# printing array
print("Elements of the array: ")
for i in range(0, len(x)):
    print(x[i], end=" ") 
print()

print(x[24])
print(x[0])
print(x[8])
print(x[-1])



array('i', [1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100])
Elements of the array: 
1 4 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79 82 85 88 91 94 97 100 
73
1
25
100


In [24]:
# Add elements in an Array

new_arr = arr.array('i', [i for i in range(2,20)])
print(new_arr)

# using insert
new_arr.insert(0,1)
print(new_arr)

new_arr.insert(10,11) # (Position, ELement)
print(new_arr)

# using append
new_arr.append(20)
print(new_arr)



array('i', [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 13, 14, 15, 16, 17, 18, 19])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


In [31]:
#Updating element value
new = arr.array('i', [1,2,2,4,5])
print(new)

new[2] = 3
print(new)

array('i', [1, 2, 2, 4, 5])
array('i', [1, 2, 3, 4, 5])


In [32]:
# Deleting elements in an array
new.pop() #by default last element delete, but can provide index number as paramater in function
print(new)

new.remove(4) # remove element by value
print(new)

array('i', [1, 2, 3, 4])
array('i', [1, 2, 3])


**Slicing**

- Slicing is the way to access a range of elements in an array.
- Syntax: array[start:stop:step]


In [38]:
x = arr.array('i', list(range(1,101,4)))
print(x)

arr0 = x[:8]
print(arr0)

arr1 = x[8:16]
print(arr1)

arr2 = x[16:]
print(arr2)

#Reversing:
x.reverse()
print(x)

x[::-1]
print(x)



array('i', [1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97])
array('i', [1, 5, 9, 13, 17, 21, 25, 29])
array('i', [33, 37, 41, 45, 49, 53, 57, 61])
array('i', [65, 69, 73, 77, 81, 85, 89, 93, 97])
array('i', [97, 93, 89, 85, 81, 77, 73, 69, 65, 61, 57, 53, 49, 45, 41, 37, 33, 29, 25, 21, 17, 13, 9, 5, 1])
array('i', [97, 93, 89, 85, 81, 77, 73, 69, 65, 61, 57, 53, 49, 45, 41, 37, 33, 29, 25, 21, 17, 13, 9, 5, 1])


In [43]:
# Searching elements in an array:
x = arr.array('i', list(range(1,1000,2)))
print(x)

print(len(x))

#first 10 elements
for i in range(0,len(x[:10])):
    print(x[i], end=" ")
print()

#last 10 elements
for i in range(0,len(x[-10:])):
    print(x[i], end=" ")
print()

#searching element
# search for number 505's index
print(x.index(505))






array('i', [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 371, 373, 375, 377, 379, 381, 383, 385, 387, 389, 391, 393, 395, 397, 399, 401, 403, 405, 407, 409, 411, 413, 415, 417

In [49]:
#Sorting:

x = arr.array('i', [4,2,5,1,3,6,7,9,8])
print(x)

x = arr.array('i', sorted(x)) #so not to convert into list
print(x)

print(type(x))


array('i', [4, 2, 5, 1, 3, 6, 7, 9, 8])
array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])
<class 'array.array'>


-----------------------------------------------------------------------------------------------------------------------------------------------

In [52]:
#Importing Numpy

import numpy as np

#Creating an array
arr = np.array([1,2,3,4,5])
print(arr)

#Creating a 2D array
arr2d = np.array(
    [[1,2,3],[4,5,6],[7,8,9]]
    )
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
